name: "service-boilerplate"
version: "3.8"

services:
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers

volumes:
  redis_data: