// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: doctor/doctor.proto

package doctor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TherapistService_Next_FullMethodName         = "/TherapistService/Next"
	TherapistService_FinalVerdict_FullMethodName = "/TherapistService/FinalVerdict"
)

// TherapistServiceClient is the client API for TherapistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TherapistServiceClient interface {
	Next(ctx context.Context, in *NextRq, opts ...grpc.CallOption) (*NextRs, error)
	FinalVerdict(ctx context.Context, in *FinalVerdictRq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type therapistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTherapistServiceClient(cc grpc.ClientConnInterface) TherapistServiceClient {
	return &therapistServiceClient{cc}
}

func (c *therapistServiceClient) Next(ctx context.Context, in *NextRq, opts ...grpc.CallOption) (*NextRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextRs)
	err := c.cc.Invoke(ctx, TherapistService_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) FinalVerdict(ctx context.Context, in *FinalVerdictRq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TherapistService_FinalVerdict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TherapistServiceServer is the server API for TherapistService service.
// All implementations must embed UnimplementedTherapistServiceServer
// for forward compatibility.
type TherapistServiceServer interface {
	Next(context.Context, *NextRq) (*NextRs, error)
	FinalVerdict(context.Context, *FinalVerdictRq) (*emptypb.Empty, error)
	mustEmbedUnimplementedTherapistServiceServer()
}

// UnimplementedTherapistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTherapistServiceServer struct{}

func (UnimplementedTherapistServiceServer) Next(context.Context, *NextRq) (*NextRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedTherapistServiceServer) FinalVerdict(context.Context, *FinalVerdictRq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalVerdict not implemented")
}
func (UnimplementedTherapistServiceServer) mustEmbedUnimplementedTherapistServiceServer() {}
func (UnimplementedTherapistServiceServer) testEmbeddedByValue()                          {}

// UnsafeTherapistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TherapistServiceServer will
// result in compilation errors.
type UnsafeTherapistServiceServer interface {
	mustEmbedUnimplementedTherapistServiceServer()
}

func RegisterTherapistServiceServer(s grpc.ServiceRegistrar, srv TherapistServiceServer) {
	// If the following call pancis, it indicates UnimplementedTherapistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TherapistService_ServiceDesc, srv)
}

func _TherapistService_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).Next(ctx, req.(*NextRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_FinalVerdict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalVerdictRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).FinalVerdict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_FinalVerdict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).FinalVerdict(ctx, req.(*FinalVerdictRq))
	}
	return interceptor(ctx, in, info, handler)
}

// TherapistService_ServiceDesc is the grpc.ServiceDesc for TherapistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TherapistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TherapistService",
	HandlerType: (*TherapistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _TherapistService_Next_Handler,
		},
		{
			MethodName: "FinalVerdict",
			Handler:    _TherapistService_FinalVerdict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doctor/doctor.proto",
}

const (
	DoctorService_Create_FullMethodName        = "/DoctorService/Create"
	DoctorService_Next_FullMethodName          = "/DoctorService/Next"
	DoctorService_GetHistory_FullMethodName    = "/DoctorService/GetHistory"
	DoctorService_GetDoctorInfo_FullMethodName = "/DoctorService/GetDoctorInfo"
	DoctorService_GetAllDoctors_FullMethodName = "/DoctorService/GetAllDoctors"
)

// DoctorServiceClient is the client API for DoctorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoctorServiceClient interface {
	Create(ctx context.Context, in *CreateRq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Next(ctx context.Context, in *NextRq, opts ...grpc.CallOption) (*NextRs, error)
	GetHistory(ctx context.Context, in *GetHistoryRq, opts ...grpc.CallOption) (*GetHistoryRs, error)
	GetDoctorInfo(ctx context.Context, in *GetDoctorInfoRq, opts ...grpc.CallOption) (*GetDoctorInfoRs, error)
	GetAllDoctors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllDoctorsRs, error)
}

type doctorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorServiceClient(cc grpc.ClientConnInterface) DoctorServiceClient {
	return &doctorServiceClient{cc}
}

func (c *doctorServiceClient) Create(ctx context.Context, in *CreateRq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DoctorService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorServiceClient) Next(ctx context.Context, in *NextRq, opts ...grpc.CallOption) (*NextRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextRs)
	err := c.cc.Invoke(ctx, DoctorService_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorServiceClient) GetHistory(ctx context.Context, in *GetHistoryRq, opts ...grpc.CallOption) (*GetHistoryRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryRs)
	err := c.cc.Invoke(ctx, DoctorService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorServiceClient) GetDoctorInfo(ctx context.Context, in *GetDoctorInfoRq, opts ...grpc.CallOption) (*GetDoctorInfoRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorInfoRs)
	err := c.cc.Invoke(ctx, DoctorService_GetDoctorInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorServiceClient) GetAllDoctors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllDoctorsRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllDoctorsRs)
	err := c.cc.Invoke(ctx, DoctorService_GetAllDoctors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorServiceServer is the server API for DoctorService service.
// All implementations must embed UnimplementedDoctorServiceServer
// for forward compatibility.
type DoctorServiceServer interface {
	Create(context.Context, *CreateRq) (*emptypb.Empty, error)
	Next(context.Context, *NextRq) (*NextRs, error)
	GetHistory(context.Context, *GetHistoryRq) (*GetHistoryRs, error)
	GetDoctorInfo(context.Context, *GetDoctorInfoRq) (*GetDoctorInfoRs, error)
	GetAllDoctors(context.Context, *emptypb.Empty) (*GetAllDoctorsRs, error)
	mustEmbedUnimplementedDoctorServiceServer()
}

// UnimplementedDoctorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoctorServiceServer struct{}

func (UnimplementedDoctorServiceServer) Create(context.Context, *CreateRq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDoctorServiceServer) Next(context.Context, *NextRq) (*NextRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedDoctorServiceServer) GetHistory(context.Context, *GetHistoryRq) (*GetHistoryRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedDoctorServiceServer) GetDoctorInfo(context.Context, *GetDoctorInfoRq) (*GetDoctorInfoRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDoctorInfo not implemented")
}
func (UnimplementedDoctorServiceServer) GetAllDoctors(context.Context, *emptypb.Empty) (*GetAllDoctorsRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDoctors not implemented")
}
func (UnimplementedDoctorServiceServer) mustEmbedUnimplementedDoctorServiceServer() {}
func (UnimplementedDoctorServiceServer) testEmbeddedByValue()                       {}

// UnsafeDoctorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorServiceServer will
// result in compilation errors.
type UnsafeDoctorServiceServer interface {
	mustEmbedUnimplementedDoctorServiceServer()
}

func RegisterDoctorServiceServer(s grpc.ServiceRegistrar, srv DoctorServiceServer) {
	// If the following call pancis, it indicates UnimplementedDoctorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoctorService_ServiceDesc, srv)
}

func _DoctorService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).Create(ctx, req.(*CreateRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorService_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).Next(ctx, req.(*NextRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).GetHistory(ctx, req.(*GetHistoryRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorService_GetDoctorInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorInfoRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).GetDoctorInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_GetDoctorInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).GetDoctorInfo(ctx, req.(*GetDoctorInfoRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorService_GetAllDoctors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).GetAllDoctors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_GetAllDoctors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).GetAllDoctors(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DoctorService_ServiceDesc is the grpc.ServiceDesc for DoctorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoctorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DoctorService",
	HandlerType: (*DoctorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DoctorService_Create_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _DoctorService_Next_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _DoctorService_GetHistory_Handler,
		},
		{
			MethodName: "GetDoctorInfo",
			Handler:    _DoctorService_GetDoctorInfo_Handler,
		},
		{
			MethodName: "GetAllDoctors",
			Handler:    _DoctorService_GetAllDoctors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doctor/doctor.proto",
}
