apiVersion: v1
kind: Pod
metadata:
  name: service_pod
  labels:
    role: service_pod
spec:
  containers:
    - name: service_pod
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: service_pod
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  